### ISSUE TITLE
bump.changelog.create not working

### ISSUE THREAD

**Issue by dobbbri** [fabiospampinato/vscode-bump#1]
I remove my changelog.md and when I run bump, not create new file changelog.md

**Comment by fabiospampinato** [comment]
I can't reproduce this, it works for me.

Are you getting any errors when running `Bump`?

**Comment by fabiospampinato** [comment]
There's an option for creating the changelog file, which is set to `false` by default.

Adding this to your settings should fix the problem:
```json
"bump.changelog.create": true
```
