### ISSUE TITLE
Unable to use bump when git root is different from workspace root.

### ISSUE THREAD

**Issue by shidil** [fabiospampinato/vscode-bump#2]
For a case like
```
project - (git root)
   --- apps
      --- app1 - (workspace root)

```

Bump shows an error message `You have to open a Git repository before being able to bump its version`

Is there a workaround for this? or is it a feature that can be added?

**Comment by fabiospampinato** [comment]
@Shidil is `app1` the only root in your Visual Studio Code workspace?

**Comment by shidil** [comment]
@fabiospampinato yes it is the only working directory in the editor

**Comment by fabiospampinato** [comment]
I'm afraid this scenario is not supported.

You should have the git root opened in Visual Studio Code, or make `app1` a git repo itself.
