### ISSUE TITLE
Message: This repository is not supported, read Bump's readme to learn more about it

### ISSUE THREAD

**Issue by diegoquintanav** [fabiospampinato/vscode-bump#3]
I've just installed Bump, did `ctrl+shift+p` > Bump and got the following error message

```
This repository is not supported, read Bump's readme to learn more about it
```

I promise I've read Bump's readme, but it is just not clear to me *why my repository is not supported*. According to the documentation, 

> Bump your project's version and update the changelog. Opinionated but configurable.
> This extension is here to save you time, this is what it can do for you:

>    It can bump your project's version.
>   It can detect which commits where made after the latest bump and update your changelog accordingly.
>    It can automatically make a commit with the changes made.
>    It can execute custom scripts before/after bumping/updating-the-changelog/committing.
>    How the changelog gets rendered and the commit message can be customized.

>It automatically detects NPM packages, and can be customized to bump the version in whatever file you need it to.
> It currently only works with Git projects.

So, should my repo be a NPM project? It is a git project. What's wrong?

**Comment by fabiospampinato** [comment]
What version are you trying to bump here exactly? 

If your project has a `package.json` file in its root it will bump that file, if you tell it which files to bump via the `bump.files` setting than it will bump those files.

Otherwise what version should it bump?
