### ISSUE TITLE
Feature request: Add date as token

### ISSUE THREAD

**Issue by Hocdoc** [fabiospampinato/vscode-bump#4]
I always include the publish date in my CHANGELOG just as described in https://keepachangelog.com/  f.ex. `[0.3.0] - 2015-12-03`.

It would be cool, if you could use the current date as token.

**Comment by fabiospampinato** [comment]
Definitely, thanks for the suggestion!

**Comment by fabiospampinato** [comment]
I've added two new tokens in v1.8.0: `[date]`, for commit-level dates, and `[version_date]`, for version-level dates.

Both formats are configurable via the settings, useful for the crazy people how use `MM-DD-YYY`.
